/**
 * GENERATED — do not edit by hand.
 *
 * Written by the assignment-04 copy pipeline
 * (`agents/build_strings.py --emit`) from string tables that passed their own
 * checker and matched the game's content exactly in both directions.
 *
 * Approved under rules fingerprint 1c105365e024f716
 * on 2026-08-23T21:58:53+00:00.
 * 108 strings, 6 tables, English and Spanish.
 *
 * Regenerate rather than editing: a hand-edit here is a string nothing checked.
 *
 * EXCEPT `ui.restart` — the pipeline script (`agents/build_strings.py`) isn't
 * part of this repo, so that one entry was added by hand rather than
 * regenerated. It still passes the drift/orphan tests in strings.test.ts, but
 * hasn't been through the copy pipeline's own two-way check. Worth running
 * through the real pipeline next time it's available.
 */
export type Lang = "en" | "es";

export const STRINGS: Record<string, { en: string; es: string }> = {
  "buff.cd_bolt.label": { en: "Quick Shuttle", es: "Lanzadera Rápida" },
  "buff.cd_bolt.text": { en: "Bolt cooldown -15%", es: "Rayo: recarga -15%" },
  "buff.cd_burst.label": { en: "Loose Knot", es: "Nudo Suelto" },
  "buff.cd_burst.text": { en: "Burst cooldown -15%", es: "Estallido: recarga -15%" },
  "buff.cd_con.label": { en: "Restless Gear", es: "Engranaje Inquieto" },
  "buff.cd_con.text": { en: "Construct cooldown -15%", es: "Constructo: recarga -15%" },
  "buff.dmg_bolt.label": { en: "Taut Thread", es: "Hilo Tenso" },
  "buff.dmg_bolt.text": { en: "Bolt damage +25%", es: "Rayo: daño +25%" },
  "buff.dmg_burst.label": { en: "Wide Weft", es: "Trama Ancha" },
  "buff.dmg_burst.text": { en: "Burst damage +25%", es: "Estallido: daño +25%" },
  "buff.dmg_con.label": { en: "Bound Servant", es: "Siervo Atado" },
  "buff.dmg_con.text": { en: "Construct damage +25%", es: "Constructo: daño +25%" },
  "buff.range.label": { en: "Long Reach", es: "Largo Alcance" },
  "buff.range.text": { en: "Relic range +12%", es: "Reliquia: alcance +12%" },
  "buff.repair.label": { en: "Mending", es: "Remiendo" },
  "buff.repair.text": { en: "Repair Beacon: 25", es: "Reparar Faro: 25" },
  "buff.ult_cd.label": { en: "Short Tether", es: "Correa Breve" },
  "buff.ult_cd.text": { en: "Ultimate cooldown -18%", es: "Definitiva: recarga -18%" },
  "buff.ult_dmg.label": { en: "Deep Draw", es: "Tiro Profundo" },
  "buff.ult_dmg.text": { en: "Ultimate damage +30%", es: "Definitiva: daño +30%" },
  "buff.ult_size.label": { en: "Wide Cast", es: "Tiro Amplio" },
  "buff.ult_size.text": { en: "Ultimate reach +25%", es: "Definitiva: alcance +25%" },
  "category.Bolt": { en: "Bolt", es: "Rayo" },
  "category.Burst": { en: "Burst", es: "Estallido" },
  "category.Construct": { en: "Construct", es: "Constructo" },
  "class.hunter.blurb": { en: "A tall loom woven single-wide. Blades spread across the lane and strike what stands furthest.", es: "Un telar alto tejido de un solo hilo. Las hojas se expanden por el carril e impactan a lo que esté más lejos." },
  "class.hunter.label": { en: "Hunter", es: "Cazador" },
  "class.titan.blurb": { en: "A wide loom that breaks outward. Sweeps threats from the Beacon and hurls them back up the lane.", es: "Un telar ancho que revienta hacia los lados. Barre amenazas del Faro y las lanza de vuelta por el carril." },
  "class.titan.label": { en: "Titan", es: "Titán" },
  "class.warden.blurb": { en: "A square loom that fits every shape. Holds ground by dragging the lane together and grinding what passes.", es: "Un telar cuadrado que cabe en cualquier forma. Sostiene el terreno juntando el carril y triturando lo que pasa." },
  "class.warden.label": { en: "Warden", es: "Guardián" },
  "relic.bolt_heavy.desc": { en: "Powerful bolts that knock back Remnants and deal heavy damage.", es: "Rayos poderosos que rechazan a los Remanentes e infligen daño severo." },
  "relic.bolt_heavy.name": { en: "Heavy Hitter", es: "Golpeador Pesado" },
  "relic.bolt_long.desc": { en: "Long-range bolts that shred armor and weaken defenses.", es: "Rayos de largo alcance que desgarran armadura y debilitan defensas." },
  "relic.bolt_long.name": { en: "Rending Bolt", es: "Rayo Desgarrador" },
  "relic.bolt_needle.desc": { en: "Precise piercing bolts that strike single targets quickly.", es: "Rayos perforantes precisos que golpean objetivos únicos rápidamente." },
  "relic.bolt_needle.name": { en: "Swift Fang", es: "Colmillo Veloz" },
  "relic.burst_arc.desc": { en: "Medium-range cone that burns Remnants over time.", es: "Cono de alcance medio que quema a los Remanentes con el tiempo." },
  "relic.burst_arc.name": { en: "Burning Arc", es: "Arco Ardiente" },
  "relic.burst_bomb.desc": { en: "Close-range burst that stuns and slows Remnants.", es: "Estallido de alcance corto que aturde y ralentiza Remanentes." },
  "relic.burst_bomb.name": { en: "Shock Burst", es: "Choque Explosivo" },
  "relic.burst_field.desc": { en: "Wide-angle cone that burns Remnants over a large area.", es: "Cono de ángulo amplio que quema a los Remanentes en un área grande." },
  "relic.burst_field.name": { en: "Flame Field", es: "Campo de Llamas" },
  "relic.construct_node.desc": { en: "Basic construct that deals steady damage to nearby Remnants.", es: "Constructo básico que inflige daño constante a los Remanentes cercanos." },
  "relic.construct_node.name": { en: "Sentry Node", es: "Nodo Centinela" },
  "relic.construct_orbit.desc": { en: "Swift swarm that slows Remnants with rapid strikes.", es: "Enjambre veloz que ralentiza a los Remanentes con golpes rápidos." },
  "relic.construct_orbit.name": { en: "Orbital Guard", es: "Guardia Orbital" },
  "relic.construct_turret.desc": { en: "Precise turret that pierces armor with focused fire.", es: "Torreta precisa que perfora armadura con fuego concentrado." },
  "relic.construct_turret.name": { en: "Focus Turret", es: "Torreta Enfocada" },
  "score.again": { en: "Try Again", es: "Reintentar" },
  "score.best": { en: "Best {n}", es: "Mejor {n}" },
  "score.class": { en: "Choose Class", es: "Elegir Clase" },
  "score.depth": { en: "Depth", es: "Profundidad" },
  "score.newbest": { en: "New Peak", es: "Nuevo Máximo" },
  "score.prose": { en: "The Beacon falls dark. Your weaving endures—proof you stood against the tide.", es: "El Faro se apaga. Tu tejido perdura: prueba de que resististe la marea." },
  "score.summary": { en: "{cls} · {relics} relics · {cells}/{unlocked} cells · {buffs} buffs · level {level}", es: "{cls} · {relics} reliquias · {cells}/{unlocked} celdas · {buffs} buffs · nivel {level}" },
  "score.title": { en: "The Beacon Fell", es: "El Faro Cayó" },
  "score.work": { en: "Damage Dealt", es: "Daño Infligido" },
  "tier.0": { en: "Common", es: "Común" },
  "tier.1": { en: "Uncommon", es: "Poco común" },
  "tier.2": { en: "Rare", es: "Raro" },
  "tier.3": { en: "Legendary", es: "Legendario" },
  "tier.4": { en: "Epic", es: "Épico" },
  "ui.buff.prompt": { en: "The Weave tightens. Choose one.", es: "El Tejido se aprieta. Elige uno." },
  "ui.expansion.prompt": { en: "Extend the Loom. {n} cells left. Click a highlighted cell.", es: "Extiende el Telar. {n} celdas restantes. Haz clic en una celda resaltada." },
  "ui.fight": { en: "▶ Fight", es: "▶ Luchar" },
  "ui.fight.discard": { en: "▶ Fight [{n}]", es: "▶ Luchar [{n}]" },
  "ui.gold.none": { en: "No gold yet", es: "Sin oro aún" },
  "ui.gold.spend": { en: "Gold doesn't carry between runs. Spend {gold}g before you go.", es: "El oro no se lleva entre partidas. Gasta {gold}o antes de irte." },
  "ui.group.all": { en: "All", es: "Todas" },
  "ui.hud": { en: "WAVE {wave}   LV {level}   {gold}g   BEACON {hp}/{max}", es: "OLA {wave}   NV {level}   {gold}o   FARO {hp}/{max}" },
  "ui.market.held": { en: "Click to place. R rotates. Drop a twin on a twin to weave. X scraps. Esc cancels.", es: "Haz clic para colocar. R gira. Deja una gemela sobre una gemela para tejer. X desecha. Esc cancela." },
  "ui.market.pack": { en: "Pack the Loom. Drag to shuffle. Drop a twin on a twin to weave.", es: "Empaca el Telar. Arrastra para reordenar. Deja una gemela sobre otra para tejer." },
  "ui.offer.banish": { en: "Banish", es: "Desterrar" },
  "ui.offer.stats": { en: "DMG {damage} | CD {cooldown}s\nCells {cells} | DPC {dpc}", es: "DÑ {damage} | REC {cooldown}s\nCeldas {cells} | D/C {dpc}" },
  "ui.offer.take": { en: "Take", es: "Tomar" },
  "ui.relic.stats": { en: "Tier {tier} | DMG {damage} | Cells {cells} | DPC {dpc}", es: "Rareza {tier} | DÑ {damage} | Celdas {cells} | D/C {dpc}" },
  "ui.reroll": { en: "Reroll {cost}g", es: "Renovar {cost}o" },
  "ui.reroll.free": { en: "Reroll Free", es: "Renovar gratis" },
  "ui.restart": { en: "↻ Restart", es: "↻ Reiniciar" },
  "ui.select.cooldown": { en: "CD {n}s", es: "REC {n}s" },
  "ui.select.geometry": { en: "{w}×{h} | {cells} cells | {exp} EXP | {total} total", es: "{w}×{h} | {cells} celdas | {exp} EXP | {total} total" },
  "ui.select.opens": { en: "Starts with: {relic}", es: "Comienza con: {relic}" },
  "ui.select.sub": { en: "A Weaver stands at the Beacon. Choose the Loom you will pack and the ultimate you will spend.", es: "Un Tejedor se yergue ante el Faro. Elige el Telar que empacarás y la definitiva que gastarás." },
  "ui.select.title": { en: "The Loom", es: "El Telar" },
  "ui.tray.count": { en: "{n} set aside", es: "{n} apartados" },
  "ui.tray.empty": { en: "Tray empty", es: "Bandeja vacía" },
  "ui.tray.full": { en: "The set-aside tray is full.", es: "La bandeja está llena." },
  "ui.tray.hint": { en: "Set aside to free space. Anything left here is discarded when battle begins.", es: "Aparta para liberar espacio. Lo que dejes aquí se descarta cuando comienza la batalla." },
  "ui.ult.notarget": { en: "No target", es: "Sin blanco" },
  "ui.ult.prompt": { en: "{ult}: {text}. Press Space to fire.", es: "{ult}: {text}. Presiona Espacio para disparar." },
  "ui.ult.ready": { en: "Ready", es: "Listo" },
  "ui.upgrade.maxed": { en: "Maxed", es: "Máximo" },
  "ui.weave.empty": { en: "The arsenal is empty. Defeat enemies to gain buffs.", es: "El arsenal está vacío. Derrota enemigos para ganar buffs." },
  "ui.weave.title": { en: "Arsenal", es: "Arsenal" },
  "ult.barrage.label": { en: "Blade Barrage", es: "Lluvia de Hojas" },
  "ult.barrage.text": { en: "Five blades fall down the lane and detonate where they land, striking multiple threats at once.", es: "Cinco hojas caen por el carril y detonan donde aterrizan, golpeando a varias amenazas a la vez." },
  "ult.vortex.label": { en: "Knot", es: "Nudo" },
  "ult.vortex.text": { en: "A knot gathers the lane and grinds it in place. Threats are drawn together but never pushed forward.", es: "Un nudo reúne el carril y lo tritura en su sitio. Las amenazas se agrupan, pero nunca son empujadas hacia adelante." },
  "ult.wave.label": { en: "Riven Wave", es: "Onda Rasgada" },
  "ult.wave.text": { en: "A surge breaks from the Beacon and throws back what stands in its path, protecting the gateway.", es: "Una onda rompe desde el Faro y lanza de vuelta lo que se interponga en su camino, protegiendo la puerta." },
  "upgrade.reinforce.desc": { en: "Max Beacon: +20", es: "Máx. Faro: +20" },
  "upgrade.reinforce.label": { en: "Reinforce", es: "Reforzar" },
  "upgrade.repair.desc": { en: "Mend Beacon: 30", es: "Remendar Faro: 30" },
  "upgrade.repair.label": { en: "Mend", es: "Remendar" },
  "upgrade.reroll.desc": { en: "{a}→{b} rerolls", es: "{a}→{b} renovaciones" },
  "upgrade.reroll.label": { en: "Spare Shuttle", es: "Lanzadera Extra" },
  "upgrade.study.desc": { en: "EXP gain +20%", es: "Ganancia EXP +20%" },
  "upgrade.study.label": { en: "Study", es: "Estudiar" },
};

export const STRINGS_FINGERPRINT = "1c105365e024f716";
